#!/bin/bash
#
# WebProtégé GWT Super Dev Mode Setup Script (Revised)
# This script prepares the environment for running WebProtégé
# using 'mvn gwt:codeserver' and 'mvn tomcat7:run'.
# It assumes webprotege.properties is handled by the Maven build.
#

# Exit on any error
set -e

# --- Configuration ---
# These are less critical now if .properties is auto-generated,
# but kept for potential future use or reference.
DATA_DIR=${WEBPROTEGE_DATA_DIR:-/srv/webprotege}
# Assuming the project source is mounted at /webprotege in the container.
WEBPROTEGE_SRC_DIR=/webprotege

echo "=== WebProtégé GWT Super Dev Mode Setup (Revised) ==="
echo "  Data Directory: $DATA_DIR"
echo "  Project Source: $WEBPROTEGE_SRC_DIR"
echo "  Note: webprotege.properties is expected to be generated by the Maven build."
echo "===================================================="

# Navigate to the webprotege project directory within the container
cd "$WEBPROTEGE_SRC_DIR"

# --- Step 1: Build all project modules ---
echo
echo "--- Building all WebProtégé modules (this may take some time)... ---"
# -Dmaven.test.skip=true: Skips compiling and running tests.
# -Pdev: Activates the 'dev' profile.
# -B: Batch mode (non-interactive).
#mvn clean install -Dmaven.test.skip=true -Pdev
echo "--- Maven build complete. ---"

# --- Step 2: Ensure data directory exists ---
# This is still important as the application will need it.
echo
echo "--- Ensuring data directory exists: $DATA_DIR ---"
mkdir -p "$DATA_DIR"
echo "Data directory $DATA_DIR is ready."

echo
echo "=================================================================="
echo "=== GWT Super Dev Mode setup complete! ==="
echo "Ensure that your Maven build correctly generated and configured webprotege.properties."
echo "You can now start WebProtégé using the commands from start-dev.sh or your VS Code tasks:"
echo "1. In one terminal (inside the container):"
echo "   cd $WEBPROTEGE_SRC_DIR && mvn gwt:codeserver -Dgwt.persistentunitcache=true -Dgwt.persistentunitcachedir=$WEBPROTEGE_SRC_DIR/.gwt_cache -Dgwt.draftCompile=true -Dgwt.localWorkers=4"
echo "2. In another terminal (inside the container):"
echo "   cd $WEBPROTEGE_SRC_DIR && mvn -Denv=dev tomcat7:run"
echo "=================================================================="