services:

  wpmongo:
    container_name: webprotege-mongodb
    image: mongo:4.1-bionic
    restart: unless-stopped
    # Remove the user constraint to run as root (default in container)
    volumes: 
      - mongodb_data:/data/db
    #  - ./.protegedata/mongodb:/data/db #Problems with permissions in windows on container fresh startup

    command: ["mongod", "--wiredTigerCacheSizeGB", "1.5", "--bind_ip_all"]
  webprotege:
    container_name: webprotege
    build:
      context: .
      args:
        - MONGODB_HOST=wpmongo
    depends_on:
      - wpmongo
    restart: unless-stopped
    environment:
      - WEBPROTEGE_MONGODB_HOST=wpmongo
    volumes: 
      - ./.protegedata/protege:/srv/webprotege
      - ./:/webprotege
    ports:
      - 5000:8080
      - 8080:8080  # Additional port for development
volumes:
  mongodb_data:
